SOLR-9570: utilsTool to rotate logs etc. Replaced in bin/solr but not in solr.cmd

diff --git a/solr/bin/solr b/solr/bin/solr
--- a/solr/bin/solr
+++ b/solr/bin/solr
@@ -1387,15 +1387,10 @@ if [ ! -e "$SOLR_HOME" ]; then
   exit 1
 fi
 
-# Archive last run GC logs TODO
-#if test -n "$(find "$SOLR_LOGS_DIR" -maxdepth 1 -name 'solr_gc_*' -print -quit)"
-
-if $(find "$SOLR_LOGS_DIR" -name solr_gc_*) ; then
-  echo "Archiving old garbage collection logs to $SOLR_LOGS_DIR/archived"
-  mkdir -p "$SOLR_LOGS_DIR/archived"
-  rm "$SOLR_LOGS_DIR/archived/*" 2>/dev/null
-  find -X "$SOLR_LOGS_DIR" -name solr_gc_* |xargs mv "$SOLR_LOGS_DIR/archived/"
-fi
+run_tool utils -remove_old_solr_logs "$SOLR_LOGS_DIR" || echo "Failed removing old solr logs"
+run_tool utils -archive_gc_logs "$SOLR_LOGS_DIR" || echo "Failed archiving old GC logs"
+run_tool utils -archive_console_logs "$SOLR_LOGS_DIR" || echo "Failed archiving old console logs"
+run_tool utils -rotate_solr_logs "$SOLR_LOGS_DIR" || echo "Failed rotating old solr logs"
 
 java_ver_out=`echo "$("$JAVA" -version 2>&1)"`
 JAVA_VERSION=`echo $java_ver_out | grep "java version" | awk '{ print substr($3, 2, length($3)-2); }'`
